/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Applications.WeShare.Swagger.Client;
using Applications.WeShare.Swagger.Api;
// uncomment below to import models
//using Applications.WeShare.Swagger.Model;

namespace Applications.WeShare.Swagger.Test.Api
{
    /// <summary>
    ///  Class for testing ExpensesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ExpensesApiTests : IDisposable
    {
        private ExpensesApi instance;

        public ExpensesApiTests()
        {
            // instance = new ExpensesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExpensesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ExpensesApi
            // Assert.IsType<ExpensesApi>(instance);
        }

        /// <summary>
        /// Test CreateExpense
        /// </summary>
        [Fact]
        public void CreateExpenseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewExpenseDTO newExpenseDTO = null;
            //var response = instance.CreateExpense(newExpenseDTO);
            //Assert.IsType<ExpenseDTO>(response);
        }

        /// <summary>
        /// Test FindAllExpenses
        /// </summary>
        [Fact]
        public void FindAllExpensesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FindAllExpenses();
            //Assert.IsType<List<ExpenseDTO>>(response);
        }

        /// <summary>
        /// Test FindExpenseById
        /// </summary>
        [Fact]
        public void FindExpenseByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int expenseId = null;
            //var response = instance.FindExpenseById(expenseId);
            //Assert.IsType<ExpenseDTO>(response);
        }

        /// <summary>
        /// Test FindExpensesByPerson
        /// </summary>
        [Fact]
        public void FindExpensesByPersonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int personId = null;
            //var response = instance.FindExpensesByPerson(personId);
            //Assert.IsType<List<ExpenseDTO>>(response);
        }
    }
}
