/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Applications.WeShare.Swagger.Api;
using Applications.WeShare.Swagger.Model;
using Applications.WeShare.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Applications.WeShare.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing ExpenseDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExpenseDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExpenseDTO
        //private ExpenseDTO instance;

        public ExpenseDTOTests()
        {
            // TODO uncomment below to create an instance of ExpenseDTO
            //instance = new ExpenseDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExpenseDTO
        /// </summary>
        [Fact]
        public void ExpenseDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExpenseDTO
            //Assert.IsType<ExpenseDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ExpenseId'
        /// </summary>
        [Fact]
        public void ExpenseIdTest()
        {
            // TODO unit test for the property 'ExpenseId'
        }
        /// <summary>
        /// Test the property 'PersonId'
        /// </summary>
        [Fact]
        public void PersonIdTest()
        {
            // TODO unit test for the property 'PersonId'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'TotalPaymentsRequested'
        /// </summary>
        [Fact]
        public void TotalPaymentsRequestedTest()
        {
            // TODO unit test for the property 'TotalPaymentsRequested'
        }
        /// <summary>
        /// Test the property 'TotalPaymentsReceived'
        /// </summary>
        [Fact]
        public void TotalPaymentsReceivedTest()
        {
            // TODO unit test for the property 'TotalPaymentsReceived'
        }
        /// <summary>
        /// Test the property 'NettAmount'
        /// </summary>
        [Fact]
        public void NettAmountTest()
        {
            // TODO unit test for the property 'NettAmount'
        }

    }

}
