/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Applications.WeShare.Swagger.Api;
using Applications.WeShare.Swagger.Model;
using Applications.WeShare.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Applications.WeShare.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing LoginDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginDTO
        //private LoginDTO instance;

        public LoginDTOTests()
        {
            // TODO uncomment below to create an instance of LoginDTO
            //instance = new LoginDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginDTO
        /// </summary>
        [Fact]
        public void LoginDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginDTO
            //Assert.IsType<LoginDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
