/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Applications.WeShare.Swagger.Api;
using Applications.WeShare.Swagger.Model;
using Applications.WeShare.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Applications.WeShare.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing NewPaymentDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewPaymentDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewPaymentDTO
        //private NewPaymentDTO instance;

        public NewPaymentDTOTests()
        {
            // TODO uncomment below to create an instance of NewPaymentDTO
            //instance = new NewPaymentDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewPaymentDTO
        /// </summary>
        [Fact]
        public void NewPaymentDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewPaymentDTO
            //Assert.IsType<NewPaymentDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ExpenseId'
        /// </summary>
        [Fact]
        public void ExpenseIdTest()
        {
            // TODO unit test for the property 'ExpenseId'
        }
        /// <summary>
        /// Test the property 'PaymentRequestId'
        /// </summary>
        [Fact]
        public void PaymentRequestIdTest()
        {
            // TODO unit test for the property 'PaymentRequestId'
        }
        /// <summary>
        /// Test the property 'PayingPersonId'
        /// </summary>
        [Fact]
        public void PayingPersonIdTest()
        {
            // TODO unit test for the property 'PayingPersonId'
        }

    }

}
