/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Applications.WeShare.Swagger.Api;
using Applications.WeShare.Swagger.Model;
using Applications.WeShare.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Applications.WeShare.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentRequestDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentRequestDTO
        //private PaymentRequestDTO instance;

        public PaymentRequestDTOTests()
        {
            // TODO uncomment below to create an instance of PaymentRequestDTO
            //instance = new PaymentRequestDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentRequestDTO
        /// </summary>
        [Fact]
        public void PaymentRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentRequestDTO
            //Assert.IsType<PaymentRequestDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExpenseId'
        /// </summary>
        [Fact]
        public void ExpenseIdTest()
        {
            // TODO unit test for the property 'ExpenseId'
        }
        /// <summary>
        /// Test the property 'FromPersonId'
        /// </summary>
        [Fact]
        public void FromPersonIdTest()
        {
            // TODO unit test for the property 'FromPersonId'
        }
        /// <summary>
        /// Test the property 'ToPersonId'
        /// </summary>
        [Fact]
        public void ToPersonIdTest()
        {
            // TODO unit test for the property 'ToPersonId'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Paid'
        /// </summary>
        [Fact]
        public void PaidTest()
        {
            // TODO unit test for the property 'Paid'
        }

    }

}
