/*
 * WeShare API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Applications.WeShare.Swagger.Api;
using Applications.WeShare.Swagger.Model;
using Applications.WeShare.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Applications.WeShare.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentDTO
        //private PaymentDTO instance;

        public PaymentDTOTests()
        {
            // TODO uncomment below to create an instance of PaymentDTO
            //instance = new PaymentDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentDTO
        /// </summary>
        [Fact]
        public void PaymentDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentDTO
            //Assert.IsType<PaymentDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExpenseId'
        /// </summary>
        [Fact]
        public void ExpenseIdTest()
        {
            // TODO unit test for the property 'ExpenseId'
        }
        /// <summary>
        /// Test the property 'PaymentRequestId'
        /// </summary>
        [Fact]
        public void PaymentRequestIdTest()
        {
            // TODO unit test for the property 'PaymentRequestId'
        }
        /// <summary>
        /// Test the property 'PayingPersonId'
        /// </summary>
        [Fact]
        public void PayingPersonIdTest()
        {
            // TODO unit test for the property 'PayingPersonId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

    }

}
